version: '3'

services:
    app:
        build: .
        volumes:
            - .:/home/node/app
            - node-modules:/home/node/app/node_modules
        ports:
            - '${PORT:-3000}:${PORT:-3000}'
        environment:
            PORT: ${PORT:-3000}

volumes:
    node-modules:
